name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run unit tests
        run: |
          cd src/tests
          pytest --alluredir=allure-results user_tests.py product_tests.py product_cart_tests.py product_order_tests.py payment_tests.py order_tests.py cart_tests.py
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit_tests
    services:
      postgres:
        image: postgres:14.5
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run integration tests
        run: |
          cd src/tests
          pytest --alluredir=allure-results integration_tests.py
  e2e_tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: integration_tests
    services:
      postgres:
        image: postgres:14.5
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run e2e tests
        run: |
          cd src/tests
          pytest --alluredir=allure-results e2e.py
