name: Docker Compose CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ../../src/docker-compose.yml  # Укажите путь к вашему docker-compose.yml
          push: false # Не пушим образ в registry
          targets: app #  Собираем только сервис 'app'
      - name: Run tests
        uses: docker/compose-action@v2
        with:
          file: ../../src/docker-compose.yml
          run: |
            docker-compose up -d --build postgres # Запускаем PostgreSQL
            docker-compose run --rm app poetry run pytest tests/ #  ОБЯЗАТЕЛЬНО укажите команду для app
            docker-compose down # Останавливаем и удаляем контейнеры
